LANG2VOICES = {
    "ar": ["kareem-medium"],
    "ca": ["upc_ona-x-low", "upc_pau-x-low"],
    "cs": ["jirka-low", "jirka-medium"],
    "da": ["nst_talesyntese-medium"],
    "de": [
        "eva_k-x-low",
        "karlsson-low",
        "kerstin-low",
        "pavoque-low",
        "ramona-low",
        "thorsten-high",
        "thorsten-low",
        "thorsten-medium",
        "thorsten_emotional-medium",
    ],
    "el": ["rapunzelina-low"],
    "en-gb": ["alan-low", "alba-medium", "southern_english_female-low"],
    "en-us": [
        "amy-low",
        "danny-low",
        "kathleen-low",
        "lessac-low",
        "lessac-medium",
        "libritts-high",
        "ryan-high",
        "ryan-low",
        "ryan-medium",
        "lessac",
    ],
    "es": [
        "ald-medium",
        "carlfm-x-low",
        "davefx-medium",
        "mls_10246-low",
        "mls_9972-low",
        "sharvard-medium",
    ],
    "fi": ["harri-low", "harri-medium"],
    "fr": ["gilles-low", "mls_1840-low", "siwis-low", "siwis-medium", "upmc-medium"],
    "hu": ["anna-medium", "berta-medium", "imre-medium"],
    "is": ["bui-medium", "salka-medium", "steinn-medium", "ugla-medium"],
    "it": ["riccardo_fasol-x-low"],
    "ka": ["natia-medium"],
    "kk": ["iseke-x-low", "issai-high", "raya-x-low"],
    "lb": ["marylux-medium"],
    "ne": ["google-medium", "google-x-low"],
    "nl": ["mls_5809-low", "mls_7432-low", "nathalie-x-low", "rdh-medium", "rdh-x-low"],
    "no": ["talesyntese-medium"],
    "pl": ["darkman-medium", "gosia-medium", "mc_speech-medium", "mls_6892-low"],
    "pt-br": ["edresson-low", "faber-medium"],
    "pt": ["tugao-medium"],
    "ro": ["mihai-medium"],
    "ru": ["irina-medium", "denis-medium", "dmitri-medium", "ruslan-medium"],
    "sk": ["lili-medium"],
    "sr": ["serbski_institut-medium"],
    "sv": ["nst-medium"],
    "sw": ["lanfrica-medium"],
    "tr": ["dfki-medium", "fahrettin-medium"],
    "uk": ["lada-x-low", "ukrainian_tts-medium"],
    "vi": ["25hours-single-low", "vais1000-medium", "vos-x-low"],
    "zh-cn": ["huayan-x-low", "huayan-medium"],
}
